// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package resoure

import (
	"github.com/AdminAce-coder/k8sctl/api/resoure"
)

type ControllerV1 struct{}

func NewV1() resoure.IResoureV1 {
	return &ControllerV1{}
}
